---
- name: Install composer latest-stable
  become: true
  ansible.builtin.get_url:
    url: '{{ composer_url }}'
    checksum: 'sha256:{{ composer_url }}.sha256sum'
    dest: "{{ composer_path }}/composer.phar"
    owner: "{{ composer_file_owner }}"
    group: "{{ composer_file_group }}"
    mode: "{{ composer_file_mode }}"
    force: "{{ composer_update }}"

- name: Symlink composer.phar
  become: true
  ansible.builtin.file:
    src: "{{ composer_path }}/composer.phar"
    dest: "{{ composer_path }}/composer"
    state: link
