---
- name: Install composer
  when: composer_uninstall == false
  block:
    - name: Install
      ansible.builtin.include_tasks: install.yml

- name: Uninstall composer
  when: composer_uninstall == true
  block:
    - name: Uninstall
      ansible.builtin.include_tasks: uninstall.yml
